---
kind: pipeline
name: default

services:
  - name: mongo
    image: mongo:4
    ports:
      - 27017

steps:
  - name: tests
    image: kennethreitz/pipenv
    environment:
      NETRANKER_CONFIG: ../config/drone-ci.py
    commands:
      - pipenv install -d
      - pipenv run python -m unittest unit_tests.py
      - sleep 5 # Give mongodb time to start
      - pipenv run python -m unittest functional_tests.py

  - name: pubilsh
    when:
      event:
        - push
    image: python:3
    environment:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD:
        from_secret: pypi_token
    commands:
      - python3 -m pip install --upgrade setuptools wheel twine
      - python3 setup.py sdist bdist_wheel
      - python3 -m twine upload dist/*

trigger:
  branch:
    - master

---
kind: signature
hmac: 2252c9323b35598569393223f5e0a16279909dfae714a201e9adb5eca0741588

...
